FROM node:20.13.1-alpine

WORKDIR /usr/src/app

RUN npm i -g @angular/cli@17.3.7
COPY package.json package-lock.json .
RUN npm install
COPY . .

RUN npm run build --prod

#Stage 2
FROM nginx:alpine
COPY --from=0 /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
