version: '3.8'
services:
  angular-app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules